services:
  redis:
    container_name: redis-minipilot
    image: redis/redis-stack:7.4.0-v0
    ports:
      - "6399:6379"
      - "8099:8001"
    volumes:
      - ./data/dump.rdb:/tmp/dump.rdb
      - ./data/entrypoint.sh:/data/entrypoint.sh
      - ./data/wrapper.sh:/data/wrapper.sh
    entrypoint: ["/bin/sh", "/data/wrapper.sh"]

  minipilot:
    build: .
    container_name: minipilot
    image: minipilot:latest
    depends_on:
      - redis
    environment:
      - DB_SERVICE=redis
      - DB_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MINIPILOT_ENDPOINT=http://127.0.0.1:8000
    ports:
      - "5007:8000"